// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dgAPi.proto

package com.hngd.rpc.dg;

public interface CommonResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hngdrpcdg.CommonResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *错误码
   * </pre>
   *
   * <code>required .hngdrpcdg.ErrorCode errorCode = 1;</code>
   */
  boolean hasErrorCode();
  /**
   * <pre>
   *错误码
   * </pre>
   *
   * <code>required .hngdrpcdg.ErrorCode errorCode = 1;</code>
   */
  com.hngd.rpc.dg.ErrorCode getErrorCode();

  /**
   * <pre>
   *错误描述信息
   * </pre>
   *
   * <code>optional string description = 2;</code>
   */
  boolean hasDescription();
  /**
   * <pre>
   *错误描述信息
   * </pre>
   *
   * <code>optional string description = 2;</code>
   */
  java.lang.String getDescription();
  /**
   * <pre>
   *错误描述信息
   * </pre>
   *
   * <code>optional string description = 2;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <pre>
   *数据
   * </pre>
   *
   * <code>optional bytes data = 3;</code>
   */
  boolean hasData();
  /**
   * <pre>
   *数据
   * </pre>
   *
   * <code>optional bytes data = 3;</code>
   */
  com.google.protobuf.ByteString getData();
}
