// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dgAPi.proto

package com.hngd.rpc.dg;

/**
 * <pre>
 *设备信息
 * </pre>
 *
 * Protobuf type {@code hngdrpcdg.DeviceInfo}
 */
public  final class DeviceInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:hngdrpcdg.DeviceInfo)
    DeviceInfoOrBuilder {
  // Use DeviceInfo.newBuilder() to construct.
  private DeviceInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DeviceInfo() {
    strDeviceCode_ = "";
    strLoginName_ = "";
    strLoginPwd_ = "";
    nPort_ = 0;
    strIP_ = "";
    nChannel_ = 0;
    deviceTypeCode_ = "";
    enVendor_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DeviceInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            strDeviceCode_ = bs;
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            strLoginName_ = bs;
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000004;
            strLoginPwd_ = bs;
            break;
          }
          case 32: {
            bitField0_ |= 0x00000008;
            nPort_ = input.readInt32();
            break;
          }
          case 42: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000010;
            strIP_ = bs;
            break;
          }
          case 48: {
            bitField0_ |= 0x00000020;
            nChannel_ = input.readInt32();
            break;
          }
          case 74: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000040;
            deviceTypeCode_ = bs;
            break;
          }
          case 82: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000080;
            enVendor_ = bs;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.hngd.rpc.dg.DgApiProto.internal_static_hngdrpcdg_DeviceInfo_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.hngd.rpc.dg.DgApiProto.internal_static_hngdrpcdg_DeviceInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.hngd.rpc.dg.DeviceInfo.class, com.hngd.rpc.dg.DeviceInfo.Builder.class);
  }

  private int bitField0_;
  public static final int STRDEVICECODE_FIELD_NUMBER = 1;
  private volatile java.lang.Object strDeviceCode_;
  /**
   * <code>required string strDeviceCode = 1;</code>
   */
  public boolean hasStrDeviceCode() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required string strDeviceCode = 1;</code>
   */
  public java.lang.String getStrDeviceCode() {
    java.lang.Object ref = strDeviceCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        strDeviceCode_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string strDeviceCode = 1;</code>
   */
  public com.google.protobuf.ByteString
      getStrDeviceCodeBytes() {
    java.lang.Object ref = strDeviceCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      strDeviceCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STRLOGINNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object strLoginName_;
  /**
   * <code>optional string strLoginName = 2;</code>
   */
  public boolean hasStrLoginName() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional string strLoginName = 2;</code>
   */
  public java.lang.String getStrLoginName() {
    java.lang.Object ref = strLoginName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        strLoginName_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string strLoginName = 2;</code>
   */
  public com.google.protobuf.ByteString
      getStrLoginNameBytes() {
    java.lang.Object ref = strLoginName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      strLoginName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STRLOGINPWD_FIELD_NUMBER = 3;
  private volatile java.lang.Object strLoginPwd_;
  /**
   * <code>optional string strLoginPwd = 3;</code>
   */
  public boolean hasStrLoginPwd() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional string strLoginPwd = 3;</code>
   */
  public java.lang.String getStrLoginPwd() {
    java.lang.Object ref = strLoginPwd_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        strLoginPwd_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string strLoginPwd = 3;</code>
   */
  public com.google.protobuf.ByteString
      getStrLoginPwdBytes() {
    java.lang.Object ref = strLoginPwd_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      strLoginPwd_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NPORT_FIELD_NUMBER = 4;
  private int nPort_;
  /**
   * <code>optional int32 nPort = 4;</code>
   */
  public boolean hasNPort() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional int32 nPort = 4;</code>
   */
  public int getNPort() {
    return nPort_;
  }

  public static final int STRIP_FIELD_NUMBER = 5;
  private volatile java.lang.Object strIP_;
  /**
   * <code>optional string strIP = 5;</code>
   */
  public boolean hasStrIP() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>optional string strIP = 5;</code>
   */
  public java.lang.String getStrIP() {
    java.lang.Object ref = strIP_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        strIP_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string strIP = 5;</code>
   */
  public com.google.protobuf.ByteString
      getStrIPBytes() {
    java.lang.Object ref = strIP_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      strIP_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NCHANNEL_FIELD_NUMBER = 6;
  private int nChannel_;
  /**
   * <code>optional int32 nChannel = 6;</code>
   */
  public boolean hasNChannel() {
    return ((bitField0_ & 0x00000020) == 0x00000020);
  }
  /**
   * <code>optional int32 nChannel = 6;</code>
   */
  public int getNChannel() {
    return nChannel_;
  }

  public static final int DEVICETYPECODE_FIELD_NUMBER = 9;
  private volatile java.lang.Object deviceTypeCode_;
  /**
   * <pre>
   *例如IPC,
   * </pre>
   *
   * <code>optional string deviceTypeCode = 9;</code>
   */
  public boolean hasDeviceTypeCode() {
    return ((bitField0_ & 0x00000040) == 0x00000040);
  }
  /**
   * <pre>
   *例如IPC,
   * </pre>
   *
   * <code>optional string deviceTypeCode = 9;</code>
   */
  public java.lang.String getDeviceTypeCode() {
    java.lang.Object ref = deviceTypeCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        deviceTypeCode_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   *例如IPC,
   * </pre>
   *
   * <code>optional string deviceTypeCode = 9;</code>
   */
  public com.google.protobuf.ByteString
      getDeviceTypeCodeBytes() {
    java.lang.Object ref = deviceTypeCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceTypeCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENVENDOR_FIELD_NUMBER = 10;
  private volatile java.lang.Object enVendor_;
  /**
   * <code>optional string enVendor = 10;</code>
   */
  public boolean hasEnVendor() {
    return ((bitField0_ & 0x00000080) == 0x00000080);
  }
  /**
   * <code>optional string enVendor = 10;</code>
   */
  public java.lang.String getEnVendor() {
    java.lang.Object ref = enVendor_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        enVendor_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string enVendor = 10;</code>
   */
  public com.google.protobuf.ByteString
      getEnVendorBytes() {
    java.lang.Object ref = enVendor_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      enVendor_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasStrDeviceCode()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, strDeviceCode_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, strLoginName_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, strLoginPwd_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeInt32(4, nPort_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, strIP_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      output.writeInt32(6, nChannel_);
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, deviceTypeCode_);
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, enVendor_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, strDeviceCode_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, strLoginName_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, strLoginPwd_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, nPort_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, strIP_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, nChannel_);
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, deviceTypeCode_);
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, enVendor_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.hngd.rpc.dg.DeviceInfo)) {
      return super.equals(obj);
    }
    com.hngd.rpc.dg.DeviceInfo other = (com.hngd.rpc.dg.DeviceInfo) obj;

    boolean result = true;
    result = result && (hasStrDeviceCode() == other.hasStrDeviceCode());
    if (hasStrDeviceCode()) {
      result = result && getStrDeviceCode()
          .equals(other.getStrDeviceCode());
    }
    result = result && (hasStrLoginName() == other.hasStrLoginName());
    if (hasStrLoginName()) {
      result = result && getStrLoginName()
          .equals(other.getStrLoginName());
    }
    result = result && (hasStrLoginPwd() == other.hasStrLoginPwd());
    if (hasStrLoginPwd()) {
      result = result && getStrLoginPwd()
          .equals(other.getStrLoginPwd());
    }
    result = result && (hasNPort() == other.hasNPort());
    if (hasNPort()) {
      result = result && (getNPort()
          == other.getNPort());
    }
    result = result && (hasStrIP() == other.hasStrIP());
    if (hasStrIP()) {
      result = result && getStrIP()
          .equals(other.getStrIP());
    }
    result = result && (hasNChannel() == other.hasNChannel());
    if (hasNChannel()) {
      result = result && (getNChannel()
          == other.getNChannel());
    }
    result = result && (hasDeviceTypeCode() == other.hasDeviceTypeCode());
    if (hasDeviceTypeCode()) {
      result = result && getDeviceTypeCode()
          .equals(other.getDeviceTypeCode());
    }
    result = result && (hasEnVendor() == other.hasEnVendor());
    if (hasEnVendor()) {
      result = result && getEnVendor()
          .equals(other.getEnVendor());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStrDeviceCode()) {
      hash = (37 * hash) + STRDEVICECODE_FIELD_NUMBER;
      hash = (53 * hash) + getStrDeviceCode().hashCode();
    }
    if (hasStrLoginName()) {
      hash = (37 * hash) + STRLOGINNAME_FIELD_NUMBER;
      hash = (53 * hash) + getStrLoginName().hashCode();
    }
    if (hasStrLoginPwd()) {
      hash = (37 * hash) + STRLOGINPWD_FIELD_NUMBER;
      hash = (53 * hash) + getStrLoginPwd().hashCode();
    }
    if (hasNPort()) {
      hash = (37 * hash) + NPORT_FIELD_NUMBER;
      hash = (53 * hash) + getNPort();
    }
    if (hasStrIP()) {
      hash = (37 * hash) + STRIP_FIELD_NUMBER;
      hash = (53 * hash) + getStrIP().hashCode();
    }
    if (hasNChannel()) {
      hash = (37 * hash) + NCHANNEL_FIELD_NUMBER;
      hash = (53 * hash) + getNChannel();
    }
    if (hasDeviceTypeCode()) {
      hash = (37 * hash) + DEVICETYPECODE_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceTypeCode().hashCode();
    }
    if (hasEnVendor()) {
      hash = (37 * hash) + ENVENDOR_FIELD_NUMBER;
      hash = (53 * hash) + getEnVendor().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.hngd.rpc.dg.DeviceInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hngd.rpc.dg.DeviceInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hngd.rpc.dg.DeviceInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hngd.rpc.dg.DeviceInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hngd.rpc.dg.DeviceInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hngd.rpc.dg.DeviceInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hngd.rpc.dg.DeviceInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hngd.rpc.dg.DeviceInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hngd.rpc.dg.DeviceInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.hngd.rpc.dg.DeviceInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hngd.rpc.dg.DeviceInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hngd.rpc.dg.DeviceInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.hngd.rpc.dg.DeviceInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *设备信息
   * </pre>
   *
   * Protobuf type {@code hngdrpcdg.DeviceInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:hngdrpcdg.DeviceInfo)
      com.hngd.rpc.dg.DeviceInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hngd.rpc.dg.DgApiProto.internal_static_hngdrpcdg_DeviceInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hngd.rpc.dg.DgApiProto.internal_static_hngdrpcdg_DeviceInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hngd.rpc.dg.DeviceInfo.class, com.hngd.rpc.dg.DeviceInfo.Builder.class);
    }

    // Construct using com.hngd.rpc.dg.DeviceInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      strDeviceCode_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      strLoginName_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      strLoginPwd_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      nPort_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      strIP_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      nChannel_ = 0;
      bitField0_ = (bitField0_ & ~0x00000020);
      deviceTypeCode_ = "";
      bitField0_ = (bitField0_ & ~0x00000040);
      enVendor_ = "";
      bitField0_ = (bitField0_ & ~0x00000080);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.hngd.rpc.dg.DgApiProto.internal_static_hngdrpcdg_DeviceInfo_descriptor;
    }

    public com.hngd.rpc.dg.DeviceInfo getDefaultInstanceForType() {
      return com.hngd.rpc.dg.DeviceInfo.getDefaultInstance();
    }

    public com.hngd.rpc.dg.DeviceInfo build() {
      com.hngd.rpc.dg.DeviceInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.hngd.rpc.dg.DeviceInfo buildPartial() {
      com.hngd.rpc.dg.DeviceInfo result = new com.hngd.rpc.dg.DeviceInfo(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.strDeviceCode_ = strDeviceCode_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.strLoginName_ = strLoginName_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.strLoginPwd_ = strLoginPwd_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.nPort_ = nPort_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      result.strIP_ = strIP_;
      if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
        to_bitField0_ |= 0x00000020;
      }
      result.nChannel_ = nChannel_;
      if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
        to_bitField0_ |= 0x00000040;
      }
      result.deviceTypeCode_ = deviceTypeCode_;
      if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
        to_bitField0_ |= 0x00000080;
      }
      result.enVendor_ = enVendor_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.hngd.rpc.dg.DeviceInfo) {
        return mergeFrom((com.hngd.rpc.dg.DeviceInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.hngd.rpc.dg.DeviceInfo other) {
      if (other == com.hngd.rpc.dg.DeviceInfo.getDefaultInstance()) return this;
      if (other.hasStrDeviceCode()) {
        bitField0_ |= 0x00000001;
        strDeviceCode_ = other.strDeviceCode_;
        onChanged();
      }
      if (other.hasStrLoginName()) {
        bitField0_ |= 0x00000002;
        strLoginName_ = other.strLoginName_;
        onChanged();
      }
      if (other.hasStrLoginPwd()) {
        bitField0_ |= 0x00000004;
        strLoginPwd_ = other.strLoginPwd_;
        onChanged();
      }
      if (other.hasNPort()) {
        setNPort(other.getNPort());
      }
      if (other.hasStrIP()) {
        bitField0_ |= 0x00000010;
        strIP_ = other.strIP_;
        onChanged();
      }
      if (other.hasNChannel()) {
        setNChannel(other.getNChannel());
      }
      if (other.hasDeviceTypeCode()) {
        bitField0_ |= 0x00000040;
        deviceTypeCode_ = other.deviceTypeCode_;
        onChanged();
      }
      if (other.hasEnVendor()) {
        bitField0_ |= 0x00000080;
        enVendor_ = other.enVendor_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      if (!hasStrDeviceCode()) {
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.hngd.rpc.dg.DeviceInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.hngd.rpc.dg.DeviceInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object strDeviceCode_ = "";
    /**
     * <code>required string strDeviceCode = 1;</code>
     */
    public boolean hasStrDeviceCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string strDeviceCode = 1;</code>
     */
    public java.lang.String getStrDeviceCode() {
      java.lang.Object ref = strDeviceCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          strDeviceCode_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string strDeviceCode = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStrDeviceCodeBytes() {
      java.lang.Object ref = strDeviceCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        strDeviceCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string strDeviceCode = 1;</code>
     */
    public Builder setStrDeviceCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      strDeviceCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string strDeviceCode = 1;</code>
     */
    public Builder clearStrDeviceCode() {
      bitField0_ = (bitField0_ & ~0x00000001);
      strDeviceCode_ = getDefaultInstance().getStrDeviceCode();
      onChanged();
      return this;
    }
    /**
     * <code>required string strDeviceCode = 1;</code>
     */
    public Builder setStrDeviceCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      strDeviceCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object strLoginName_ = "";
    /**
     * <code>optional string strLoginName = 2;</code>
     */
    public boolean hasStrLoginName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string strLoginName = 2;</code>
     */
    public java.lang.String getStrLoginName() {
      java.lang.Object ref = strLoginName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          strLoginName_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string strLoginName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getStrLoginNameBytes() {
      java.lang.Object ref = strLoginName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        strLoginName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string strLoginName = 2;</code>
     */
    public Builder setStrLoginName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      strLoginName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string strLoginName = 2;</code>
     */
    public Builder clearStrLoginName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      strLoginName_ = getDefaultInstance().getStrLoginName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string strLoginName = 2;</code>
     */
    public Builder setStrLoginNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      strLoginName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object strLoginPwd_ = "";
    /**
     * <code>optional string strLoginPwd = 3;</code>
     */
    public boolean hasStrLoginPwd() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string strLoginPwd = 3;</code>
     */
    public java.lang.String getStrLoginPwd() {
      java.lang.Object ref = strLoginPwd_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          strLoginPwd_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string strLoginPwd = 3;</code>
     */
    public com.google.protobuf.ByteString
        getStrLoginPwdBytes() {
      java.lang.Object ref = strLoginPwd_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        strLoginPwd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string strLoginPwd = 3;</code>
     */
    public Builder setStrLoginPwd(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      strLoginPwd_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string strLoginPwd = 3;</code>
     */
    public Builder clearStrLoginPwd() {
      bitField0_ = (bitField0_ & ~0x00000004);
      strLoginPwd_ = getDefaultInstance().getStrLoginPwd();
      onChanged();
      return this;
    }
    /**
     * <code>optional string strLoginPwd = 3;</code>
     */
    public Builder setStrLoginPwdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      strLoginPwd_ = value;
      onChanged();
      return this;
    }

    private int nPort_ ;
    /**
     * <code>optional int32 nPort = 4;</code>
     */
    public boolean hasNPort() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 nPort = 4;</code>
     */
    public int getNPort() {
      return nPort_;
    }
    /**
     * <code>optional int32 nPort = 4;</code>
     */
    public Builder setNPort(int value) {
      bitField0_ |= 0x00000008;
      nPort_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 nPort = 4;</code>
     */
    public Builder clearNPort() {
      bitField0_ = (bitField0_ & ~0x00000008);
      nPort_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object strIP_ = "";
    /**
     * <code>optional string strIP = 5;</code>
     */
    public boolean hasStrIP() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string strIP = 5;</code>
     */
    public java.lang.String getStrIP() {
      java.lang.Object ref = strIP_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          strIP_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string strIP = 5;</code>
     */
    public com.google.protobuf.ByteString
        getStrIPBytes() {
      java.lang.Object ref = strIP_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        strIP_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string strIP = 5;</code>
     */
    public Builder setStrIP(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      strIP_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string strIP = 5;</code>
     */
    public Builder clearStrIP() {
      bitField0_ = (bitField0_ & ~0x00000010);
      strIP_ = getDefaultInstance().getStrIP();
      onChanged();
      return this;
    }
    /**
     * <code>optional string strIP = 5;</code>
     */
    public Builder setStrIPBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      strIP_ = value;
      onChanged();
      return this;
    }

    private int nChannel_ ;
    /**
     * <code>optional int32 nChannel = 6;</code>
     */
    public boolean hasNChannel() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 nChannel = 6;</code>
     */
    public int getNChannel() {
      return nChannel_;
    }
    /**
     * <code>optional int32 nChannel = 6;</code>
     */
    public Builder setNChannel(int value) {
      bitField0_ |= 0x00000020;
      nChannel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 nChannel = 6;</code>
     */
    public Builder clearNChannel() {
      bitField0_ = (bitField0_ & ~0x00000020);
      nChannel_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object deviceTypeCode_ = "";
    /**
     * <pre>
     *例如IPC,
     * </pre>
     *
     * <code>optional string deviceTypeCode = 9;</code>
     */
    public boolean hasDeviceTypeCode() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <pre>
     *例如IPC,
     * </pre>
     *
     * <code>optional string deviceTypeCode = 9;</code>
     */
    public java.lang.String getDeviceTypeCode() {
      java.lang.Object ref = deviceTypeCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceTypeCode_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *例如IPC,
     * </pre>
     *
     * <code>optional string deviceTypeCode = 9;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceTypeCodeBytes() {
      java.lang.Object ref = deviceTypeCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceTypeCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *例如IPC,
     * </pre>
     *
     * <code>optional string deviceTypeCode = 9;</code>
     */
    public Builder setDeviceTypeCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      deviceTypeCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *例如IPC,
     * </pre>
     *
     * <code>optional string deviceTypeCode = 9;</code>
     */
    public Builder clearDeviceTypeCode() {
      bitField0_ = (bitField0_ & ~0x00000040);
      deviceTypeCode_ = getDefaultInstance().getDeviceTypeCode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *例如IPC,
     * </pre>
     *
     * <code>optional string deviceTypeCode = 9;</code>
     */
    public Builder setDeviceTypeCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      deviceTypeCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object enVendor_ = "";
    /**
     * <code>optional string enVendor = 10;</code>
     */
    public boolean hasEnVendor() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string enVendor = 10;</code>
     */
    public java.lang.String getEnVendor() {
      java.lang.Object ref = enVendor_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          enVendor_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string enVendor = 10;</code>
     */
    public com.google.protobuf.ByteString
        getEnVendorBytes() {
      java.lang.Object ref = enVendor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        enVendor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string enVendor = 10;</code>
     */
    public Builder setEnVendor(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
      enVendor_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string enVendor = 10;</code>
     */
    public Builder clearEnVendor() {
      bitField0_ = (bitField0_ & ~0x00000080);
      enVendor_ = getDefaultInstance().getEnVendor();
      onChanged();
      return this;
    }
    /**
     * <code>optional string enVendor = 10;</code>
     */
    public Builder setEnVendorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
      enVendor_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:hngdrpcdg.DeviceInfo)
  }

  // @@protoc_insertion_point(class_scope:hngdrpcdg.DeviceInfo)
  private static final com.hngd.rpc.dg.DeviceInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.hngd.rpc.dg.DeviceInfo();
  }

  public static com.hngd.rpc.dg.DeviceInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<DeviceInfo>
      PARSER = new com.google.protobuf.AbstractParser<DeviceInfo>() {
    public DeviceInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeviceInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DeviceInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DeviceInfo> getParserForType() {
    return PARSER;
  }

  public com.hngd.rpc.dg.DeviceInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

