// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dgAPi.proto

package com.hngd.rpc.dg;

public final class DgApiProto {
  private DgApiProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hngdrpcdg_DeviceInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hngdrpcdg_DeviceInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hngdrpcdg_DoorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hngdrpcdg_DoorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hngdrpcdg_ITCTalkOperationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hngdrpcdg_ITCTalkOperationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hngdrpcdg_RecordQueryParam_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hngdrpcdg_RecordQueryParam_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hngdrpcdg_QuryFileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hngdrpcdg_QuryFileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hngdrpcdg_PerTaskRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hngdrpcdg_PerTaskRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hngdrpcdg_CommonResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hngdrpcdg_CommonResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013dgAPi.proto\022\thngdrpcdg\"\250\001\n\nDeviceInfo\022" +
      "\025\n\rstrDeviceCode\030\001 \002(\t\022\024\n\014strLoginName\030\002" +
      " \001(\t\022\023\n\013strLoginPwd\030\003 \001(\t\022\r\n\005nPort\030\004 \001(\005" +
      "\022\r\n\005strIP\030\005 \001(\t\022\020\n\010nChannel\030\006 \001(\005\022\026\n\016dev" +
      "iceTypeCode\030\t \001(\t\022\020\n\010enVendor\030\n \001(\t\"`\n\013D" +
      "oorRequest\022&\n\007devInfo\030\001 \002(\0132\025.hngdrpcdg." +
      "DeviceInfo\022)\n\ndoorStatus\030\002 \001(\0162\025.hngdrpc" +
      "dg.DoorStatus\"\246\001\n\027ITCTalkOperationReques" +
      "t\022&\n\007devInfo\030\001 \002(\0132\025.hngdrpcdg.DeviceInf" +
      "o\022)\n\004iocd\030\002 \002(\0162\033.hngdrpcdg.ITCOperation",
      "Code\022\021\n\tfromTrmId\030\003 \001(\005\022\020\n\010toTrmIds\030\004 \001(" +
      "\t\022\023\n\013acceptTrmID\030\005 \001(\005\"[\n\020RecordQueryPar" +
      "am\022\021\n\tsubStream\030\001 \001(\005\022\020\n\010fileType\030\002 \001(\t\022" +
      "\021\n\tstartTime\030\003 \001(\003\022\017\n\007endTime\030\004 \001(\003\"l\n\017Q" +
      "uryFileRequest\022&\n\007devInfo\030\001 \003(\0132\025.hngdrp" +
      "cdg.DeviceInfo\0221\n\014reQueryParam\030\002 \001(\0132\033.h" +
      "ngdrpcdg.RecordQueryParam\"|\n\016PerTaskRequ" +
      "est\022&\n\007devInfo\030\001 \003(\0132\025.hngdrpcdg.DeviceI" +
      "nfo\0221\n\014reQueryParam\030\002 \001(\0132\033.hngdrpcdg.Re" +
      "cordQueryParam\022\017\n\007perSecs\030\003 \001(\005\"\\\n\016Commo",
      "nResponse\022\'\n\terrorCode\030\001 \002(\0162\024.hngdrpcdg" +
      ".ErrorCode\022\023\n\013description\030\002 \001(\t\022\014\n\004data\030" +
      "\003 \001(\014*8\n\nDoorStatus\022\t\n\005CLOSE\020\000\022\r\n\tOPEN_O" +
      "NCE\020\001\022\020\n\014OPEN_ALLWAYS\020\002*+\n\tErrorCode\022\006\n\002" +
      "OK\020\000\022\n\n\006FAILED\020\001\022\n\n\006OTHERS\020\002*t\n\020ITCOpera" +
      "tionCode\022\023\n\017IOC_SPEECHSTART\020\000\022\022\n\016IOC_SPE" +
      "ECHSTOP\020\001\022\021\n\rIOC_TALKSTART\020\002\022\020\n\014IOC_TALK" +
      "STOP\020\003\022\022\n\016IOC_TALKACCEPT\020\004*)\n\nConfigType" +
      "\022\007\n\003ADD\020\000\022\007\n\003DEL\020\001\022\t\n\005CLEAR\020\0022\277\002\n\005DgApi\022" +
      "D\n\rSetDoorStatus\022\026.hngdrpcdg.DoorRequest",
      "\032\031.hngdrpcdg.CommonResponse\"\000\022S\n\020ITCTalk" +
      "Operation\022\".hngdrpcdg.ITCTalkOperationRe" +
      "quest\032\031.hngdrpcdg.CommonResponse\"\000\022M\n\022Qu" +
      "eryFileOperation\022\032.hngdrpcdg.QuryFileReq" +
      "uest\032\031.hngdrpcdg.CommonResponse\"\000\022L\n\022Per" +
      "iodicTaskConfig\022\031.hngdrpcdg.PerTaskReque" +
      "st\032\031.hngdrpcdg.CommonResponse\"\000B\037\n\017com.h" +
      "ngd.rpc.dgB\nDgApiProtoP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_hngdrpcdg_DeviceInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hngdrpcdg_DeviceInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hngdrpcdg_DeviceInfo_descriptor,
        new java.lang.String[] { "StrDeviceCode", "StrLoginName", "StrLoginPwd", "NPort", "StrIP", "NChannel", "DeviceTypeCode", "EnVendor", });
    internal_static_hngdrpcdg_DoorRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_hngdrpcdg_DoorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hngdrpcdg_DoorRequest_descriptor,
        new java.lang.String[] { "DevInfo", "DoorStatus", });
    internal_static_hngdrpcdg_ITCTalkOperationRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_hngdrpcdg_ITCTalkOperationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hngdrpcdg_ITCTalkOperationRequest_descriptor,
        new java.lang.String[] { "DevInfo", "Iocd", "FromTrmId", "ToTrmIds", "AcceptTrmID", });
    internal_static_hngdrpcdg_RecordQueryParam_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_hngdrpcdg_RecordQueryParam_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hngdrpcdg_RecordQueryParam_descriptor,
        new java.lang.String[] { "SubStream", "FileType", "StartTime", "EndTime", });
    internal_static_hngdrpcdg_QuryFileRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_hngdrpcdg_QuryFileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hngdrpcdg_QuryFileRequest_descriptor,
        new java.lang.String[] { "DevInfo", "ReQueryParam", });
    internal_static_hngdrpcdg_PerTaskRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_hngdrpcdg_PerTaskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hngdrpcdg_PerTaskRequest_descriptor,
        new java.lang.String[] { "DevInfo", "ReQueryParam", "PerSecs", });
    internal_static_hngdrpcdg_CommonResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_hngdrpcdg_CommonResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hngdrpcdg_CommonResponse_descriptor,
        new java.lang.String[] { "ErrorCode", "Description", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
