// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dgAPi.proto

package com.hngd.rpc.dg;

/**
 * <pre>
 *门禁类开关门请求
 * </pre>
 *
 * Protobuf type {@code hngdrpcdg.DoorRequest}
 */
public  final class DoorRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:hngdrpcdg.DoorRequest)
    DoorRequestOrBuilder {
  // Use DoorRequest.newBuilder() to construct.
  private DoorRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DoorRequest() {
    doorStatus_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DoorRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.hngd.rpc.dg.DeviceInfo.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
              subBuilder = devInfo_.toBuilder();
            }
            devInfo_ = input.readMessage(com.hngd.rpc.dg.DeviceInfo.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(devInfo_);
              devInfo_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();
            com.hngd.rpc.dg.DoorStatus value = com.hngd.rpc.dg.DoorStatus.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(2, rawValue);
            } else {
              bitField0_ |= 0x00000002;
              doorStatus_ = rawValue;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.hngd.rpc.dg.DgApiProto.internal_static_hngdrpcdg_DoorRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.hngd.rpc.dg.DgApiProto.internal_static_hngdrpcdg_DoorRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.hngd.rpc.dg.DoorRequest.class, com.hngd.rpc.dg.DoorRequest.Builder.class);
  }

  private int bitField0_;
  public static final int DEVINFO_FIELD_NUMBER = 1;
  private com.hngd.rpc.dg.DeviceInfo devInfo_;
  /**
   * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
   */
  public boolean hasDevInfo() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
   */
  public com.hngd.rpc.dg.DeviceInfo getDevInfo() {
    return devInfo_ == null ? com.hngd.rpc.dg.DeviceInfo.getDefaultInstance() : devInfo_;
  }
  /**
   * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
   */
  public com.hngd.rpc.dg.DeviceInfoOrBuilder getDevInfoOrBuilder() {
    return devInfo_ == null ? com.hngd.rpc.dg.DeviceInfo.getDefaultInstance() : devInfo_;
  }

  public static final int DOORSTATUS_FIELD_NUMBER = 2;
  private int doorStatus_;
  /**
   * <code>optional .hngdrpcdg.DoorStatus doorStatus = 2;</code>
   */
  public boolean hasDoorStatus() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional .hngdrpcdg.DoorStatus doorStatus = 2;</code>
   */
  public com.hngd.rpc.dg.DoorStatus getDoorStatus() {
    com.hngd.rpc.dg.DoorStatus result = com.hngd.rpc.dg.DoorStatus.valueOf(doorStatus_);
    return result == null ? com.hngd.rpc.dg.DoorStatus.CLOSE : result;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasDevInfo()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getDevInfo().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeMessage(1, getDevInfo());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeEnum(2, doorStatus_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getDevInfo());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, doorStatus_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.hngd.rpc.dg.DoorRequest)) {
      return super.equals(obj);
    }
    com.hngd.rpc.dg.DoorRequest other = (com.hngd.rpc.dg.DoorRequest) obj;

    boolean result = true;
    result = result && (hasDevInfo() == other.hasDevInfo());
    if (hasDevInfo()) {
      result = result && getDevInfo()
          .equals(other.getDevInfo());
    }
    result = result && (hasDoorStatus() == other.hasDoorStatus());
    if (hasDoorStatus()) {
      result = result && doorStatus_ == other.doorStatus_;
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasDevInfo()) {
      hash = (37 * hash) + DEVINFO_FIELD_NUMBER;
      hash = (53 * hash) + getDevInfo().hashCode();
    }
    if (hasDoorStatus()) {
      hash = (37 * hash) + DOORSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + doorStatus_;
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.hngd.rpc.dg.DoorRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hngd.rpc.dg.DoorRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hngd.rpc.dg.DoorRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hngd.rpc.dg.DoorRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hngd.rpc.dg.DoorRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hngd.rpc.dg.DoorRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hngd.rpc.dg.DoorRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hngd.rpc.dg.DoorRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hngd.rpc.dg.DoorRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.hngd.rpc.dg.DoorRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hngd.rpc.dg.DoorRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hngd.rpc.dg.DoorRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.hngd.rpc.dg.DoorRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *门禁类开关门请求
   * </pre>
   *
   * Protobuf type {@code hngdrpcdg.DoorRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:hngdrpcdg.DoorRequest)
      com.hngd.rpc.dg.DoorRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hngd.rpc.dg.DgApiProto.internal_static_hngdrpcdg_DoorRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hngd.rpc.dg.DgApiProto.internal_static_hngdrpcdg_DoorRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hngd.rpc.dg.DoorRequest.class, com.hngd.rpc.dg.DoorRequest.Builder.class);
    }

    // Construct using com.hngd.rpc.dg.DoorRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDevInfoFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (devInfoBuilder_ == null) {
        devInfo_ = null;
      } else {
        devInfoBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      doorStatus_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.hngd.rpc.dg.DgApiProto.internal_static_hngdrpcdg_DoorRequest_descriptor;
    }

    public com.hngd.rpc.dg.DoorRequest getDefaultInstanceForType() {
      return com.hngd.rpc.dg.DoorRequest.getDefaultInstance();
    }

    public com.hngd.rpc.dg.DoorRequest build() {
      com.hngd.rpc.dg.DoorRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.hngd.rpc.dg.DoorRequest buildPartial() {
      com.hngd.rpc.dg.DoorRequest result = new com.hngd.rpc.dg.DoorRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      if (devInfoBuilder_ == null) {
        result.devInfo_ = devInfo_;
      } else {
        result.devInfo_ = devInfoBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.doorStatus_ = doorStatus_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.hngd.rpc.dg.DoorRequest) {
        return mergeFrom((com.hngd.rpc.dg.DoorRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.hngd.rpc.dg.DoorRequest other) {
      if (other == com.hngd.rpc.dg.DoorRequest.getDefaultInstance()) return this;
      if (other.hasDevInfo()) {
        mergeDevInfo(other.getDevInfo());
      }
      if (other.hasDoorStatus()) {
        setDoorStatus(other.getDoorStatus());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      if (!hasDevInfo()) {
        return false;
      }
      if (!getDevInfo().isInitialized()) {
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.hngd.rpc.dg.DoorRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.hngd.rpc.dg.DoorRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.hngd.rpc.dg.DeviceInfo devInfo_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.hngd.rpc.dg.DeviceInfo, com.hngd.rpc.dg.DeviceInfo.Builder, com.hngd.rpc.dg.DeviceInfoOrBuilder> devInfoBuilder_;
    /**
     * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
     */
    public boolean hasDevInfo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
     */
    public com.hngd.rpc.dg.DeviceInfo getDevInfo() {
      if (devInfoBuilder_ == null) {
        return devInfo_ == null ? com.hngd.rpc.dg.DeviceInfo.getDefaultInstance() : devInfo_;
      } else {
        return devInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
     */
    public Builder setDevInfo(com.hngd.rpc.dg.DeviceInfo value) {
      if (devInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        devInfo_ = value;
        onChanged();
      } else {
        devInfoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
     */
    public Builder setDevInfo(
        com.hngd.rpc.dg.DeviceInfo.Builder builderForValue) {
      if (devInfoBuilder_ == null) {
        devInfo_ = builderForValue.build();
        onChanged();
      } else {
        devInfoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
     */
    public Builder mergeDevInfo(com.hngd.rpc.dg.DeviceInfo value) {
      if (devInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            devInfo_ != null &&
            devInfo_ != com.hngd.rpc.dg.DeviceInfo.getDefaultInstance()) {
          devInfo_ =
            com.hngd.rpc.dg.DeviceInfo.newBuilder(devInfo_).mergeFrom(value).buildPartial();
        } else {
          devInfo_ = value;
        }
        onChanged();
      } else {
        devInfoBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
     */
    public Builder clearDevInfo() {
      if (devInfoBuilder_ == null) {
        devInfo_ = null;
        onChanged();
      } else {
        devInfoBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
     */
    public com.hngd.rpc.dg.DeviceInfo.Builder getDevInfoBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getDevInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
     */
    public com.hngd.rpc.dg.DeviceInfoOrBuilder getDevInfoOrBuilder() {
      if (devInfoBuilder_ != null) {
        return devInfoBuilder_.getMessageOrBuilder();
      } else {
        return devInfo_ == null ?
            com.hngd.rpc.dg.DeviceInfo.getDefaultInstance() : devInfo_;
      }
    }
    /**
     * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.hngd.rpc.dg.DeviceInfo, com.hngd.rpc.dg.DeviceInfo.Builder, com.hngd.rpc.dg.DeviceInfoOrBuilder> 
        getDevInfoFieldBuilder() {
      if (devInfoBuilder_ == null) {
        devInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.hngd.rpc.dg.DeviceInfo, com.hngd.rpc.dg.DeviceInfo.Builder, com.hngd.rpc.dg.DeviceInfoOrBuilder>(
                getDevInfo(),
                getParentForChildren(),
                isClean());
        devInfo_ = null;
      }
      return devInfoBuilder_;
    }

    private int doorStatus_ = 0;
    /**
     * <code>optional .hngdrpcdg.DoorStatus doorStatus = 2;</code>
     */
    public boolean hasDoorStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .hngdrpcdg.DoorStatus doorStatus = 2;</code>
     */
    public com.hngd.rpc.dg.DoorStatus getDoorStatus() {
      com.hngd.rpc.dg.DoorStatus result = com.hngd.rpc.dg.DoorStatus.valueOf(doorStatus_);
      return result == null ? com.hngd.rpc.dg.DoorStatus.CLOSE : result;
    }
    /**
     * <code>optional .hngdrpcdg.DoorStatus doorStatus = 2;</code>
     */
    public Builder setDoorStatus(com.hngd.rpc.dg.DoorStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      doorStatus_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .hngdrpcdg.DoorStatus doorStatus = 2;</code>
     */
    public Builder clearDoorStatus() {
      bitField0_ = (bitField0_ & ~0x00000002);
      doorStatus_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:hngdrpcdg.DoorRequest)
  }

  // @@protoc_insertion_point(class_scope:hngdrpcdg.DoorRequest)
  private static final com.hngd.rpc.dg.DoorRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.hngd.rpc.dg.DoorRequest();
  }

  public static com.hngd.rpc.dg.DoorRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<DoorRequest>
      PARSER = new com.google.protobuf.AbstractParser<DoorRequest>() {
    public DoorRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new DoorRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DoorRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DoorRequest> getParserForType() {
    return PARSER;
  }

  public com.hngd.rpc.dg.DoorRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

