// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dgAPi.proto

package com.hngd.rpc.dg;

/**
 * <pre>
 *门的状态
 * </pre>
 *
 * Protobuf enum {@code hngdrpcdg.DoorStatus}
 */
public enum DoorStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   *关门
   * </pre>
   *
   * <code>CLOSE = 0;</code>
   */
  CLOSE(0),
  /**
   * <pre>
   *开门（短开，开门后自动延时关门）
   * </pre>
   *
   * <code>OPEN_ONCE = 1;</code>
   */
  OPEN_ONCE(1),
  /**
   * <pre>
   *开门（长开）
   * </pre>
   *
   * <code>OPEN_ALLWAYS = 2;</code>
   */
  OPEN_ALLWAYS(2),
  ;

  /**
   * <pre>
   *关门
   * </pre>
   *
   * <code>CLOSE = 0;</code>
   */
  public static final int CLOSE_VALUE = 0;
  /**
   * <pre>
   *开门（短开，开门后自动延时关门）
   * </pre>
   *
   * <code>OPEN_ONCE = 1;</code>
   */
  public static final int OPEN_ONCE_VALUE = 1;
  /**
   * <pre>
   *开门（长开）
   * </pre>
   *
   * <code>OPEN_ALLWAYS = 2;</code>
   */
  public static final int OPEN_ALLWAYS_VALUE = 2;


  public final int getNumber() {
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static DoorStatus valueOf(int value) {
    return forNumber(value);
  }

  public static DoorStatus forNumber(int value) {
    switch (value) {
      case 0: return CLOSE;
      case 1: return OPEN_ONCE;
      case 2: return OPEN_ALLWAYS;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<DoorStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      DoorStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<DoorStatus>() {
          public DoorStatus findValueByNumber(int number) {
            return DoorStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.hngd.rpc.dg.DgApiProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final DoorStatus[] VALUES = values();

  public static DoorStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private DoorStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:hngdrpcdg.DoorStatus)
}

