// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dgAPi.proto

package com.hngd.rpc.dg;

public interface DoorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hngdrpcdg.DoorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
   */
  boolean hasDevInfo();
  /**
   * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
   */
  com.hngd.rpc.dg.DeviceInfo getDevInfo();
  /**
   * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
   */
  com.hngd.rpc.dg.DeviceInfoOrBuilder getDevInfoOrBuilder();

  /**
   * <code>optional .hngdrpcdg.DoorStatus doorStatus = 2;</code>
   */
  boolean hasDoorStatus();
  /**
   * <code>optional .hngdrpcdg.DoorStatus doorStatus = 2;</code>
   */
  com.hngd.rpc.dg.DoorStatus getDoorStatus();
}
