// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dgAPi.proto

package com.hngd.rpc.dg;

/**
 * <pre>
 *ITC语音对讲操作
 * </pre>
 *
 * Protobuf type {@code hngdrpcdg.ITCTalkOperationRequest}
 */
public  final class ITCTalkOperationRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:hngdrpcdg.ITCTalkOperationRequest)
    ITCTalkOperationRequestOrBuilder {
  // Use ITCTalkOperationRequest.newBuilder() to construct.
  private ITCTalkOperationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ITCTalkOperationRequest() {
    iocd_ = 0;
    fromTrmId_ = 0;
    toTrmIds_ = "";
    acceptTrmID_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ITCTalkOperationRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.hngd.rpc.dg.DeviceInfo.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
              subBuilder = devInfo_.toBuilder();
            }
            devInfo_ = input.readMessage(com.hngd.rpc.dg.DeviceInfo.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(devInfo_);
              devInfo_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();
            com.hngd.rpc.dg.ITCOperationCode value = com.hngd.rpc.dg.ITCOperationCode.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(2, rawValue);
            } else {
              bitField0_ |= 0x00000002;
              iocd_ = rawValue;
            }
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            fromTrmId_ = input.readInt32();
            break;
          }
          case 34: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000008;
            toTrmIds_ = bs;
            break;
          }
          case 40: {
            bitField0_ |= 0x00000010;
            acceptTrmID_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.hngd.rpc.dg.DgApiProto.internal_static_hngdrpcdg_ITCTalkOperationRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.hngd.rpc.dg.DgApiProto.internal_static_hngdrpcdg_ITCTalkOperationRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.hngd.rpc.dg.ITCTalkOperationRequest.class, com.hngd.rpc.dg.ITCTalkOperationRequest.Builder.class);
  }

  private int bitField0_;
  public static final int DEVINFO_FIELD_NUMBER = 1;
  private com.hngd.rpc.dg.DeviceInfo devInfo_;
  /**
   * <pre>
   *ITC对接软件的信息即为设备信息
   * </pre>
   *
   * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
   */
  public boolean hasDevInfo() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <pre>
   *ITC对接软件的信息即为设备信息
   * </pre>
   *
   * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
   */
  public com.hngd.rpc.dg.DeviceInfo getDevInfo() {
    return devInfo_ == null ? com.hngd.rpc.dg.DeviceInfo.getDefaultInstance() : devInfo_;
  }
  /**
   * <pre>
   *ITC对接软件的信息即为设备信息
   * </pre>
   *
   * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
   */
  public com.hngd.rpc.dg.DeviceInfoOrBuilder getDevInfoOrBuilder() {
    return devInfo_ == null ? com.hngd.rpc.dg.DeviceInfo.getDefaultInstance() : devInfo_;
  }

  public static final int IOCD_FIELD_NUMBER = 2;
  private int iocd_;
  /**
   * <code>required .hngdrpcdg.ITCOperationCode iocd = 2;</code>
   */
  public boolean hasIocd() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required .hngdrpcdg.ITCOperationCode iocd = 2;</code>
   */
  public com.hngd.rpc.dg.ITCOperationCode getIocd() {
    com.hngd.rpc.dg.ITCOperationCode result = com.hngd.rpc.dg.ITCOperationCode.valueOf(iocd_);
    return result == null ? com.hngd.rpc.dg.ITCOperationCode.IOC_SPEECHSTART : result;
  }

  public static final int FROMTRMID_FIELD_NUMBER = 3;
  private int fromTrmId_;
  /**
   * <pre>
   *发起者终端ID;
   * </pre>
   *
   * <code>optional int32 fromTrmId = 3;</code>
   */
  public boolean hasFromTrmId() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <pre>
   *发起者终端ID;
   * </pre>
   *
   * <code>optional int32 fromTrmId = 3;</code>
   */
  public int getFromTrmId() {
    return fromTrmId_;
  }

  public static final int TOTRMIDS_FIELD_NUMBER = 4;
  private volatile java.lang.Object toTrmIds_;
  /**
   * <pre>
   *寻呼接收者终端ID，可能有多个，用逗号分隔。对讲接收者终端ID只有1个
   * </pre>
   *
   * <code>optional string toTrmIds = 4;</code>
   */
  public boolean hasToTrmIds() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <pre>
   *寻呼接收者终端ID，可能有多个，用逗号分隔。对讲接收者终端ID只有1个
   * </pre>
   *
   * <code>optional string toTrmIds = 4;</code>
   */
  public java.lang.String getToTrmIds() {
    java.lang.Object ref = toTrmIds_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        toTrmIds_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   *寻呼接收者终端ID，可能有多个，用逗号分隔。对讲接收者终端ID只有1个
   * </pre>
   *
   * <code>optional string toTrmIds = 4;</code>
   */
  public com.google.protobuf.ByteString
      getToTrmIdsBytes() {
    java.lang.Object ref = toTrmIds_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      toTrmIds_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACCEPTTRMID_FIELD_NUMBER = 5;
  private int acceptTrmID_;
  /**
   * <pre>
   *接收对讲者终端ID
   * </pre>
   *
   * <code>optional int32 acceptTrmID = 5;</code>
   */
  public boolean hasAcceptTrmID() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <pre>
   *接收对讲者终端ID
   * </pre>
   *
   * <code>optional int32 acceptTrmID = 5;</code>
   */
  public int getAcceptTrmID() {
    return acceptTrmID_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasDevInfo()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasIocd()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getDevInfo().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeMessage(1, getDevInfo());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeEnum(2, iocd_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeInt32(3, fromTrmId_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, toTrmIds_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeInt32(5, acceptTrmID_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getDevInfo());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, iocd_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, fromTrmId_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, toTrmIds_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, acceptTrmID_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.hngd.rpc.dg.ITCTalkOperationRequest)) {
      return super.equals(obj);
    }
    com.hngd.rpc.dg.ITCTalkOperationRequest other = (com.hngd.rpc.dg.ITCTalkOperationRequest) obj;

    boolean result = true;
    result = result && (hasDevInfo() == other.hasDevInfo());
    if (hasDevInfo()) {
      result = result && getDevInfo()
          .equals(other.getDevInfo());
    }
    result = result && (hasIocd() == other.hasIocd());
    if (hasIocd()) {
      result = result && iocd_ == other.iocd_;
    }
    result = result && (hasFromTrmId() == other.hasFromTrmId());
    if (hasFromTrmId()) {
      result = result && (getFromTrmId()
          == other.getFromTrmId());
    }
    result = result && (hasToTrmIds() == other.hasToTrmIds());
    if (hasToTrmIds()) {
      result = result && getToTrmIds()
          .equals(other.getToTrmIds());
    }
    result = result && (hasAcceptTrmID() == other.hasAcceptTrmID());
    if (hasAcceptTrmID()) {
      result = result && (getAcceptTrmID()
          == other.getAcceptTrmID());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasDevInfo()) {
      hash = (37 * hash) + DEVINFO_FIELD_NUMBER;
      hash = (53 * hash) + getDevInfo().hashCode();
    }
    if (hasIocd()) {
      hash = (37 * hash) + IOCD_FIELD_NUMBER;
      hash = (53 * hash) + iocd_;
    }
    if (hasFromTrmId()) {
      hash = (37 * hash) + FROMTRMID_FIELD_NUMBER;
      hash = (53 * hash) + getFromTrmId();
    }
    if (hasToTrmIds()) {
      hash = (37 * hash) + TOTRMIDS_FIELD_NUMBER;
      hash = (53 * hash) + getToTrmIds().hashCode();
    }
    if (hasAcceptTrmID()) {
      hash = (37 * hash) + ACCEPTTRMID_FIELD_NUMBER;
      hash = (53 * hash) + getAcceptTrmID();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.hngd.rpc.dg.ITCTalkOperationRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hngd.rpc.dg.ITCTalkOperationRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hngd.rpc.dg.ITCTalkOperationRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hngd.rpc.dg.ITCTalkOperationRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hngd.rpc.dg.ITCTalkOperationRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hngd.rpc.dg.ITCTalkOperationRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hngd.rpc.dg.ITCTalkOperationRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hngd.rpc.dg.ITCTalkOperationRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hngd.rpc.dg.ITCTalkOperationRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.hngd.rpc.dg.ITCTalkOperationRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hngd.rpc.dg.ITCTalkOperationRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hngd.rpc.dg.ITCTalkOperationRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.hngd.rpc.dg.ITCTalkOperationRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *ITC语音对讲操作
   * </pre>
   *
   * Protobuf type {@code hngdrpcdg.ITCTalkOperationRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:hngdrpcdg.ITCTalkOperationRequest)
      com.hngd.rpc.dg.ITCTalkOperationRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hngd.rpc.dg.DgApiProto.internal_static_hngdrpcdg_ITCTalkOperationRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hngd.rpc.dg.DgApiProto.internal_static_hngdrpcdg_ITCTalkOperationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hngd.rpc.dg.ITCTalkOperationRequest.class, com.hngd.rpc.dg.ITCTalkOperationRequest.Builder.class);
    }

    // Construct using com.hngd.rpc.dg.ITCTalkOperationRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDevInfoFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (devInfoBuilder_ == null) {
        devInfo_ = null;
      } else {
        devInfoBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      iocd_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      fromTrmId_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      toTrmIds_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      acceptTrmID_ = 0;
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.hngd.rpc.dg.DgApiProto.internal_static_hngdrpcdg_ITCTalkOperationRequest_descriptor;
    }

    public com.hngd.rpc.dg.ITCTalkOperationRequest getDefaultInstanceForType() {
      return com.hngd.rpc.dg.ITCTalkOperationRequest.getDefaultInstance();
    }

    public com.hngd.rpc.dg.ITCTalkOperationRequest build() {
      com.hngd.rpc.dg.ITCTalkOperationRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.hngd.rpc.dg.ITCTalkOperationRequest buildPartial() {
      com.hngd.rpc.dg.ITCTalkOperationRequest result = new com.hngd.rpc.dg.ITCTalkOperationRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      if (devInfoBuilder_ == null) {
        result.devInfo_ = devInfo_;
      } else {
        result.devInfo_ = devInfoBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.iocd_ = iocd_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.fromTrmId_ = fromTrmId_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.toTrmIds_ = toTrmIds_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      result.acceptTrmID_ = acceptTrmID_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.hngd.rpc.dg.ITCTalkOperationRequest) {
        return mergeFrom((com.hngd.rpc.dg.ITCTalkOperationRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.hngd.rpc.dg.ITCTalkOperationRequest other) {
      if (other == com.hngd.rpc.dg.ITCTalkOperationRequest.getDefaultInstance()) return this;
      if (other.hasDevInfo()) {
        mergeDevInfo(other.getDevInfo());
      }
      if (other.hasIocd()) {
        setIocd(other.getIocd());
      }
      if (other.hasFromTrmId()) {
        setFromTrmId(other.getFromTrmId());
      }
      if (other.hasToTrmIds()) {
        bitField0_ |= 0x00000008;
        toTrmIds_ = other.toTrmIds_;
        onChanged();
      }
      if (other.hasAcceptTrmID()) {
        setAcceptTrmID(other.getAcceptTrmID());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      if (!hasDevInfo()) {
        return false;
      }
      if (!hasIocd()) {
        return false;
      }
      if (!getDevInfo().isInitialized()) {
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.hngd.rpc.dg.ITCTalkOperationRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.hngd.rpc.dg.ITCTalkOperationRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.hngd.rpc.dg.DeviceInfo devInfo_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.hngd.rpc.dg.DeviceInfo, com.hngd.rpc.dg.DeviceInfo.Builder, com.hngd.rpc.dg.DeviceInfoOrBuilder> devInfoBuilder_;
    /**
     * <pre>
     *ITC对接软件的信息即为设备信息
     * </pre>
     *
     * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
     */
    public boolean hasDevInfo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *ITC对接软件的信息即为设备信息
     * </pre>
     *
     * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
     */
    public com.hngd.rpc.dg.DeviceInfo getDevInfo() {
      if (devInfoBuilder_ == null) {
        return devInfo_ == null ? com.hngd.rpc.dg.DeviceInfo.getDefaultInstance() : devInfo_;
      } else {
        return devInfoBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *ITC对接软件的信息即为设备信息
     * </pre>
     *
     * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
     */
    public Builder setDevInfo(com.hngd.rpc.dg.DeviceInfo value) {
      if (devInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        devInfo_ = value;
        onChanged();
      } else {
        devInfoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     *ITC对接软件的信息即为设备信息
     * </pre>
     *
     * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
     */
    public Builder setDevInfo(
        com.hngd.rpc.dg.DeviceInfo.Builder builderForValue) {
      if (devInfoBuilder_ == null) {
        devInfo_ = builderForValue.build();
        onChanged();
      } else {
        devInfoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     *ITC对接软件的信息即为设备信息
     * </pre>
     *
     * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
     */
    public Builder mergeDevInfo(com.hngd.rpc.dg.DeviceInfo value) {
      if (devInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            devInfo_ != null &&
            devInfo_ != com.hngd.rpc.dg.DeviceInfo.getDefaultInstance()) {
          devInfo_ =
            com.hngd.rpc.dg.DeviceInfo.newBuilder(devInfo_).mergeFrom(value).buildPartial();
        } else {
          devInfo_ = value;
        }
        onChanged();
      } else {
        devInfoBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     *ITC对接软件的信息即为设备信息
     * </pre>
     *
     * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
     */
    public Builder clearDevInfo() {
      if (devInfoBuilder_ == null) {
        devInfo_ = null;
        onChanged();
      } else {
        devInfoBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <pre>
     *ITC对接软件的信息即为设备信息
     * </pre>
     *
     * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
     */
    public com.hngd.rpc.dg.DeviceInfo.Builder getDevInfoBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getDevInfoFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *ITC对接软件的信息即为设备信息
     * </pre>
     *
     * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
     */
    public com.hngd.rpc.dg.DeviceInfoOrBuilder getDevInfoOrBuilder() {
      if (devInfoBuilder_ != null) {
        return devInfoBuilder_.getMessageOrBuilder();
      } else {
        return devInfo_ == null ?
            com.hngd.rpc.dg.DeviceInfo.getDefaultInstance() : devInfo_;
      }
    }
    /**
     * <pre>
     *ITC对接软件的信息即为设备信息
     * </pre>
     *
     * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.hngd.rpc.dg.DeviceInfo, com.hngd.rpc.dg.DeviceInfo.Builder, com.hngd.rpc.dg.DeviceInfoOrBuilder> 
        getDevInfoFieldBuilder() {
      if (devInfoBuilder_ == null) {
        devInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.hngd.rpc.dg.DeviceInfo, com.hngd.rpc.dg.DeviceInfo.Builder, com.hngd.rpc.dg.DeviceInfoOrBuilder>(
                getDevInfo(),
                getParentForChildren(),
                isClean());
        devInfo_ = null;
      }
      return devInfoBuilder_;
    }

    private int iocd_ = 0;
    /**
     * <code>required .hngdrpcdg.ITCOperationCode iocd = 2;</code>
     */
    public boolean hasIocd() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .hngdrpcdg.ITCOperationCode iocd = 2;</code>
     */
    public com.hngd.rpc.dg.ITCOperationCode getIocd() {
      com.hngd.rpc.dg.ITCOperationCode result = com.hngd.rpc.dg.ITCOperationCode.valueOf(iocd_);
      return result == null ? com.hngd.rpc.dg.ITCOperationCode.IOC_SPEECHSTART : result;
    }
    /**
     * <code>required .hngdrpcdg.ITCOperationCode iocd = 2;</code>
     */
    public Builder setIocd(com.hngd.rpc.dg.ITCOperationCode value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      iocd_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>required .hngdrpcdg.ITCOperationCode iocd = 2;</code>
     */
    public Builder clearIocd() {
      bitField0_ = (bitField0_ & ~0x00000002);
      iocd_ = 0;
      onChanged();
      return this;
    }

    private int fromTrmId_ ;
    /**
     * <pre>
     *发起者终端ID;
     * </pre>
     *
     * <code>optional int32 fromTrmId = 3;</code>
     */
    public boolean hasFromTrmId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     *发起者终端ID;
     * </pre>
     *
     * <code>optional int32 fromTrmId = 3;</code>
     */
    public int getFromTrmId() {
      return fromTrmId_;
    }
    /**
     * <pre>
     *发起者终端ID;
     * </pre>
     *
     * <code>optional int32 fromTrmId = 3;</code>
     */
    public Builder setFromTrmId(int value) {
      bitField0_ |= 0x00000004;
      fromTrmId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *发起者终端ID;
     * </pre>
     *
     * <code>optional int32 fromTrmId = 3;</code>
     */
    public Builder clearFromTrmId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      fromTrmId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object toTrmIds_ = "";
    /**
     * <pre>
     *寻呼接收者终端ID，可能有多个，用逗号分隔。对讲接收者终端ID只有1个
     * </pre>
     *
     * <code>optional string toTrmIds = 4;</code>
     */
    public boolean hasToTrmIds() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     *寻呼接收者终端ID，可能有多个，用逗号分隔。对讲接收者终端ID只有1个
     * </pre>
     *
     * <code>optional string toTrmIds = 4;</code>
     */
    public java.lang.String getToTrmIds() {
      java.lang.Object ref = toTrmIds_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          toTrmIds_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *寻呼接收者终端ID，可能有多个，用逗号分隔。对讲接收者终端ID只有1个
     * </pre>
     *
     * <code>optional string toTrmIds = 4;</code>
     */
    public com.google.protobuf.ByteString
        getToTrmIdsBytes() {
      java.lang.Object ref = toTrmIds_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toTrmIds_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *寻呼接收者终端ID，可能有多个，用逗号分隔。对讲接收者终端ID只有1个
     * </pre>
     *
     * <code>optional string toTrmIds = 4;</code>
     */
    public Builder setToTrmIds(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      toTrmIds_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *寻呼接收者终端ID，可能有多个，用逗号分隔。对讲接收者终端ID只有1个
     * </pre>
     *
     * <code>optional string toTrmIds = 4;</code>
     */
    public Builder clearToTrmIds() {
      bitField0_ = (bitField0_ & ~0x00000008);
      toTrmIds_ = getDefaultInstance().getToTrmIds();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *寻呼接收者终端ID，可能有多个，用逗号分隔。对讲接收者终端ID只有1个
     * </pre>
     *
     * <code>optional string toTrmIds = 4;</code>
     */
    public Builder setToTrmIdsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      toTrmIds_ = value;
      onChanged();
      return this;
    }

    private int acceptTrmID_ ;
    /**
     * <pre>
     *接收对讲者终端ID
     * </pre>
     *
     * <code>optional int32 acceptTrmID = 5;</code>
     */
    public boolean hasAcceptTrmID() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     *接收对讲者终端ID
     * </pre>
     *
     * <code>optional int32 acceptTrmID = 5;</code>
     */
    public int getAcceptTrmID() {
      return acceptTrmID_;
    }
    /**
     * <pre>
     *接收对讲者终端ID
     * </pre>
     *
     * <code>optional int32 acceptTrmID = 5;</code>
     */
    public Builder setAcceptTrmID(int value) {
      bitField0_ |= 0x00000010;
      acceptTrmID_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *接收对讲者终端ID
     * </pre>
     *
     * <code>optional int32 acceptTrmID = 5;</code>
     */
    public Builder clearAcceptTrmID() {
      bitField0_ = (bitField0_ & ~0x00000010);
      acceptTrmID_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:hngdrpcdg.ITCTalkOperationRequest)
  }

  // @@protoc_insertion_point(class_scope:hngdrpcdg.ITCTalkOperationRequest)
  private static final com.hngd.rpc.dg.ITCTalkOperationRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.hngd.rpc.dg.ITCTalkOperationRequest();
  }

  public static com.hngd.rpc.dg.ITCTalkOperationRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<ITCTalkOperationRequest>
      PARSER = new com.google.protobuf.AbstractParser<ITCTalkOperationRequest>() {
    public ITCTalkOperationRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ITCTalkOperationRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ITCTalkOperationRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ITCTalkOperationRequest> getParserForType() {
    return PARSER;
  }

  public com.hngd.rpc.dg.ITCTalkOperationRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

