// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dgAPi.proto

package com.hngd.rpc.dg;

public interface ITCTalkOperationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hngdrpcdg.ITCTalkOperationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *ITC对接软件的信息即为设备信息
   * </pre>
   *
   * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
   */
  boolean hasDevInfo();
  /**
   * <pre>
   *ITC对接软件的信息即为设备信息
   * </pre>
   *
   * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
   */
  com.hngd.rpc.dg.DeviceInfo getDevInfo();
  /**
   * <pre>
   *ITC对接软件的信息即为设备信息
   * </pre>
   *
   * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
   */
  com.hngd.rpc.dg.DeviceInfoOrBuilder getDevInfoOrBuilder();

  /**
   * <code>required .hngdrpcdg.ITCOperationCode iocd = 2;</code>
   */
  boolean hasIocd();
  /**
   * <code>required .hngdrpcdg.ITCOperationCode iocd = 2;</code>
   */
  com.hngd.rpc.dg.ITCOperationCode getIocd();

  /**
   * <pre>
   *发起者终端ID;
   * </pre>
   *
   * <code>optional int32 fromTrmId = 3;</code>
   */
  boolean hasFromTrmId();
  /**
   * <pre>
   *发起者终端ID;
   * </pre>
   *
   * <code>optional int32 fromTrmId = 3;</code>
   */
  int getFromTrmId();

  /**
   * <pre>
   *寻呼接收者终端ID，可能有多个，用逗号分隔。对讲接收者终端ID只有1个
   * </pre>
   *
   * <code>optional string toTrmIds = 4;</code>
   */
  boolean hasToTrmIds();
  /**
   * <pre>
   *寻呼接收者终端ID，可能有多个，用逗号分隔。对讲接收者终端ID只有1个
   * </pre>
   *
   * <code>optional string toTrmIds = 4;</code>
   */
  java.lang.String getToTrmIds();
  /**
   * <pre>
   *寻呼接收者终端ID，可能有多个，用逗号分隔。对讲接收者终端ID只有1个
   * </pre>
   *
   * <code>optional string toTrmIds = 4;</code>
   */
  com.google.protobuf.ByteString
      getToTrmIdsBytes();

  /**
   * <pre>
   *接收对讲者终端ID
   * </pre>
   *
   * <code>optional int32 acceptTrmID = 5;</code>
   */
  boolean hasAcceptTrmID();
  /**
   * <pre>
   *接收对讲者终端ID
   * </pre>
   *
   * <code>optional int32 acceptTrmID = 5;</code>
   */
  int getAcceptTrmID();
}
