// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dgAPi.proto

package com.hngd.rpc.dg;

public interface PerTaskRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hngdrpcdg.PerTaskRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .hngdrpcdg.DeviceInfo devInfo = 1;</code>
   */
  java.util.List<com.hngd.rpc.dg.DeviceInfo> 
      getDevInfoList();
  /**
   * <code>repeated .hngdrpcdg.DeviceInfo devInfo = 1;</code>
   */
  com.hngd.rpc.dg.DeviceInfo getDevInfo(int index);
  /**
   * <code>repeated .hngdrpcdg.DeviceInfo devInfo = 1;</code>
   */
  int getDevInfoCount();
  /**
   * <code>repeated .hngdrpcdg.DeviceInfo devInfo = 1;</code>
   */
  java.util.List<? extends com.hngd.rpc.dg.DeviceInfoOrBuilder> 
      getDevInfoOrBuilderList();
  /**
   * <code>repeated .hngdrpcdg.DeviceInfo devInfo = 1;</code>
   */
  com.hngd.rpc.dg.DeviceInfoOrBuilder getDevInfoOrBuilder(
      int index);

  /**
   * <code>optional .hngdrpcdg.RecordQueryParam reQueryParam = 2;</code>
   */
  boolean hasReQueryParam();
  /**
   * <code>optional .hngdrpcdg.RecordQueryParam reQueryParam = 2;</code>
   */
  com.hngd.rpc.dg.RecordQueryParam getReQueryParam();
  /**
   * <code>optional .hngdrpcdg.RecordQueryParam reQueryParam = 2;</code>
   */
  com.hngd.rpc.dg.RecordQueryParamOrBuilder getReQueryParamOrBuilder();

  /**
   * <pre>
   *循环周期，单位：秒
   * </pre>
   *
   * <code>optional int32 perSecs = 3;</code>
   */
  boolean hasPerSecs();
  /**
   * <pre>
   *循环周期，单位：秒
   * </pre>
   *
   * <code>optional int32 perSecs = 3;</code>
   */
  int getPerSecs();
}
