// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dgAPi.proto

package com.hngd.rpc.dg;

/**
 * <pre>
 *周期任务配置请求
 * </pre>
 *
 * Protobuf type {@code hngdrpcdg.PerTaskRequest}
 */
public  final class PerTaskRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:hngdrpcdg.PerTaskRequest)
    PerTaskRequestOrBuilder {
  // Use PerTaskRequest.newBuilder() to construct.
  private PerTaskRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PerTaskRequest() {
    perSecs_ = 0;
    taskID_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PerTaskRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.hngd.rpc.dg.DeviceInfo.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
              subBuilder = devInfo_.toBuilder();
            }
            devInfo_ = input.readMessage(com.hngd.rpc.dg.DeviceInfo.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(devInfo_);
              devInfo_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          case 18: {
            com.hngd.rpc.dg.RecordQueryParam.Builder subBuilder = null;
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
              subBuilder = reQueryParam_.toBuilder();
            }
            reQueryParam_ = input.readMessage(com.hngd.rpc.dg.RecordQueryParam.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(reQueryParam_);
              reQueryParam_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000002;
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            perSecs_ = input.readInt32();
            break;
          }
          case 34: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000008;
            taskID_ = bs;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.hngd.rpc.dg.DgApiProto.internal_static_hngdrpcdg_PerTaskRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.hngd.rpc.dg.DgApiProto.internal_static_hngdrpcdg_PerTaskRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.hngd.rpc.dg.PerTaskRequest.class, com.hngd.rpc.dg.PerTaskRequest.Builder.class);
  }

  private int bitField0_;
  public static final int DEVINFO_FIELD_NUMBER = 1;
  private com.hngd.rpc.dg.DeviceInfo devInfo_;
  /**
   * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
   */
  public boolean hasDevInfo() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
   */
  public com.hngd.rpc.dg.DeviceInfo getDevInfo() {
    return devInfo_ == null ? com.hngd.rpc.dg.DeviceInfo.getDefaultInstance() : devInfo_;
  }
  /**
   * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
   */
  public com.hngd.rpc.dg.DeviceInfoOrBuilder getDevInfoOrBuilder() {
    return devInfo_ == null ? com.hngd.rpc.dg.DeviceInfo.getDefaultInstance() : devInfo_;
  }

  public static final int REQUERYPARAM_FIELD_NUMBER = 2;
  private com.hngd.rpc.dg.RecordQueryParam reQueryParam_;
  /**
   * <code>optional .hngdrpcdg.RecordQueryParam reQueryParam = 2;</code>
   */
  public boolean hasReQueryParam() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional .hngdrpcdg.RecordQueryParam reQueryParam = 2;</code>
   */
  public com.hngd.rpc.dg.RecordQueryParam getReQueryParam() {
    return reQueryParam_ == null ? com.hngd.rpc.dg.RecordQueryParam.getDefaultInstance() : reQueryParam_;
  }
  /**
   * <code>optional .hngdrpcdg.RecordQueryParam reQueryParam = 2;</code>
   */
  public com.hngd.rpc.dg.RecordQueryParamOrBuilder getReQueryParamOrBuilder() {
    return reQueryParam_ == null ? com.hngd.rpc.dg.RecordQueryParam.getDefaultInstance() : reQueryParam_;
  }

  public static final int PERSECS_FIELD_NUMBER = 3;
  private int perSecs_;
  /**
   * <pre>
   *循环周期，单位：秒
   * </pre>
   *
   * <code>optional int32 perSecs = 3;</code>
   */
  public boolean hasPerSecs() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <pre>
   *循环周期，单位：秒
   * </pre>
   *
   * <code>optional int32 perSecs = 3;</code>
   */
  public int getPerSecs() {
    return perSecs_;
  }

  public static final int TASKID_FIELD_NUMBER = 4;
  private volatile java.lang.Object taskID_;
  /**
   * <pre>
   *任务ID（CMS根据任务ID关联查询应答）
   * </pre>
   *
   * <code>optional string taskID = 4;</code>
   */
  public boolean hasTaskID() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <pre>
   *任务ID（CMS根据任务ID关联查询应答）
   * </pre>
   *
   * <code>optional string taskID = 4;</code>
   */
  public java.lang.String getTaskID() {
    java.lang.Object ref = taskID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        taskID_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   *任务ID（CMS根据任务ID关联查询应答）
   * </pre>
   *
   * <code>optional string taskID = 4;</code>
   */
  public com.google.protobuf.ByteString
      getTaskIDBytes() {
    java.lang.Object ref = taskID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      taskID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasDevInfo()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getDevInfo().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeMessage(1, getDevInfo());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeMessage(2, getReQueryParam());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeInt32(3, perSecs_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, taskID_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getDevInfo());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getReQueryParam());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, perSecs_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, taskID_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.hngd.rpc.dg.PerTaskRequest)) {
      return super.equals(obj);
    }
    com.hngd.rpc.dg.PerTaskRequest other = (com.hngd.rpc.dg.PerTaskRequest) obj;

    boolean result = true;
    result = result && (hasDevInfo() == other.hasDevInfo());
    if (hasDevInfo()) {
      result = result && getDevInfo()
          .equals(other.getDevInfo());
    }
    result = result && (hasReQueryParam() == other.hasReQueryParam());
    if (hasReQueryParam()) {
      result = result && getReQueryParam()
          .equals(other.getReQueryParam());
    }
    result = result && (hasPerSecs() == other.hasPerSecs());
    if (hasPerSecs()) {
      result = result && (getPerSecs()
          == other.getPerSecs());
    }
    result = result && (hasTaskID() == other.hasTaskID());
    if (hasTaskID()) {
      result = result && getTaskID()
          .equals(other.getTaskID());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasDevInfo()) {
      hash = (37 * hash) + DEVINFO_FIELD_NUMBER;
      hash = (53 * hash) + getDevInfo().hashCode();
    }
    if (hasReQueryParam()) {
      hash = (37 * hash) + REQUERYPARAM_FIELD_NUMBER;
      hash = (53 * hash) + getReQueryParam().hashCode();
    }
    if (hasPerSecs()) {
      hash = (37 * hash) + PERSECS_FIELD_NUMBER;
      hash = (53 * hash) + getPerSecs();
    }
    if (hasTaskID()) {
      hash = (37 * hash) + TASKID_FIELD_NUMBER;
      hash = (53 * hash) + getTaskID().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.hngd.rpc.dg.PerTaskRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hngd.rpc.dg.PerTaskRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hngd.rpc.dg.PerTaskRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hngd.rpc.dg.PerTaskRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hngd.rpc.dg.PerTaskRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hngd.rpc.dg.PerTaskRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hngd.rpc.dg.PerTaskRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hngd.rpc.dg.PerTaskRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hngd.rpc.dg.PerTaskRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.hngd.rpc.dg.PerTaskRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hngd.rpc.dg.PerTaskRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hngd.rpc.dg.PerTaskRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.hngd.rpc.dg.PerTaskRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *周期任务配置请求
   * </pre>
   *
   * Protobuf type {@code hngdrpcdg.PerTaskRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:hngdrpcdg.PerTaskRequest)
      com.hngd.rpc.dg.PerTaskRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hngd.rpc.dg.DgApiProto.internal_static_hngdrpcdg_PerTaskRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hngd.rpc.dg.DgApiProto.internal_static_hngdrpcdg_PerTaskRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hngd.rpc.dg.PerTaskRequest.class, com.hngd.rpc.dg.PerTaskRequest.Builder.class);
    }

    // Construct using com.hngd.rpc.dg.PerTaskRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDevInfoFieldBuilder();
        getReQueryParamFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (devInfoBuilder_ == null) {
        devInfo_ = null;
      } else {
        devInfoBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (reQueryParamBuilder_ == null) {
        reQueryParam_ = null;
      } else {
        reQueryParamBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      perSecs_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      taskID_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.hngd.rpc.dg.DgApiProto.internal_static_hngdrpcdg_PerTaskRequest_descriptor;
    }

    public com.hngd.rpc.dg.PerTaskRequest getDefaultInstanceForType() {
      return com.hngd.rpc.dg.PerTaskRequest.getDefaultInstance();
    }

    public com.hngd.rpc.dg.PerTaskRequest build() {
      com.hngd.rpc.dg.PerTaskRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.hngd.rpc.dg.PerTaskRequest buildPartial() {
      com.hngd.rpc.dg.PerTaskRequest result = new com.hngd.rpc.dg.PerTaskRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      if (devInfoBuilder_ == null) {
        result.devInfo_ = devInfo_;
      } else {
        result.devInfo_ = devInfoBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      if (reQueryParamBuilder_ == null) {
        result.reQueryParam_ = reQueryParam_;
      } else {
        result.reQueryParam_ = reQueryParamBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.perSecs_ = perSecs_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.taskID_ = taskID_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.hngd.rpc.dg.PerTaskRequest) {
        return mergeFrom((com.hngd.rpc.dg.PerTaskRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.hngd.rpc.dg.PerTaskRequest other) {
      if (other == com.hngd.rpc.dg.PerTaskRequest.getDefaultInstance()) return this;
      if (other.hasDevInfo()) {
        mergeDevInfo(other.getDevInfo());
      }
      if (other.hasReQueryParam()) {
        mergeReQueryParam(other.getReQueryParam());
      }
      if (other.hasPerSecs()) {
        setPerSecs(other.getPerSecs());
      }
      if (other.hasTaskID()) {
        bitField0_ |= 0x00000008;
        taskID_ = other.taskID_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      if (!hasDevInfo()) {
        return false;
      }
      if (!getDevInfo().isInitialized()) {
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.hngd.rpc.dg.PerTaskRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.hngd.rpc.dg.PerTaskRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.hngd.rpc.dg.DeviceInfo devInfo_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.hngd.rpc.dg.DeviceInfo, com.hngd.rpc.dg.DeviceInfo.Builder, com.hngd.rpc.dg.DeviceInfoOrBuilder> devInfoBuilder_;
    /**
     * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
     */
    public boolean hasDevInfo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
     */
    public com.hngd.rpc.dg.DeviceInfo getDevInfo() {
      if (devInfoBuilder_ == null) {
        return devInfo_ == null ? com.hngd.rpc.dg.DeviceInfo.getDefaultInstance() : devInfo_;
      } else {
        return devInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
     */
    public Builder setDevInfo(com.hngd.rpc.dg.DeviceInfo value) {
      if (devInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        devInfo_ = value;
        onChanged();
      } else {
        devInfoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
     */
    public Builder setDevInfo(
        com.hngd.rpc.dg.DeviceInfo.Builder builderForValue) {
      if (devInfoBuilder_ == null) {
        devInfo_ = builderForValue.build();
        onChanged();
      } else {
        devInfoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
     */
    public Builder mergeDevInfo(com.hngd.rpc.dg.DeviceInfo value) {
      if (devInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            devInfo_ != null &&
            devInfo_ != com.hngd.rpc.dg.DeviceInfo.getDefaultInstance()) {
          devInfo_ =
            com.hngd.rpc.dg.DeviceInfo.newBuilder(devInfo_).mergeFrom(value).buildPartial();
        } else {
          devInfo_ = value;
        }
        onChanged();
      } else {
        devInfoBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
     */
    public Builder clearDevInfo() {
      if (devInfoBuilder_ == null) {
        devInfo_ = null;
        onChanged();
      } else {
        devInfoBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
     */
    public com.hngd.rpc.dg.DeviceInfo.Builder getDevInfoBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getDevInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
     */
    public com.hngd.rpc.dg.DeviceInfoOrBuilder getDevInfoOrBuilder() {
      if (devInfoBuilder_ != null) {
        return devInfoBuilder_.getMessageOrBuilder();
      } else {
        return devInfo_ == null ?
            com.hngd.rpc.dg.DeviceInfo.getDefaultInstance() : devInfo_;
      }
    }
    /**
     * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.hngd.rpc.dg.DeviceInfo, com.hngd.rpc.dg.DeviceInfo.Builder, com.hngd.rpc.dg.DeviceInfoOrBuilder> 
        getDevInfoFieldBuilder() {
      if (devInfoBuilder_ == null) {
        devInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.hngd.rpc.dg.DeviceInfo, com.hngd.rpc.dg.DeviceInfo.Builder, com.hngd.rpc.dg.DeviceInfoOrBuilder>(
                getDevInfo(),
                getParentForChildren(),
                isClean());
        devInfo_ = null;
      }
      return devInfoBuilder_;
    }

    private com.hngd.rpc.dg.RecordQueryParam reQueryParam_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.hngd.rpc.dg.RecordQueryParam, com.hngd.rpc.dg.RecordQueryParam.Builder, com.hngd.rpc.dg.RecordQueryParamOrBuilder> reQueryParamBuilder_;
    /**
     * <code>optional .hngdrpcdg.RecordQueryParam reQueryParam = 2;</code>
     */
    public boolean hasReQueryParam() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .hngdrpcdg.RecordQueryParam reQueryParam = 2;</code>
     */
    public com.hngd.rpc.dg.RecordQueryParam getReQueryParam() {
      if (reQueryParamBuilder_ == null) {
        return reQueryParam_ == null ? com.hngd.rpc.dg.RecordQueryParam.getDefaultInstance() : reQueryParam_;
      } else {
        return reQueryParamBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .hngdrpcdg.RecordQueryParam reQueryParam = 2;</code>
     */
    public Builder setReQueryParam(com.hngd.rpc.dg.RecordQueryParam value) {
      if (reQueryParamBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        reQueryParam_ = value;
        onChanged();
      } else {
        reQueryParamBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .hngdrpcdg.RecordQueryParam reQueryParam = 2;</code>
     */
    public Builder setReQueryParam(
        com.hngd.rpc.dg.RecordQueryParam.Builder builderForValue) {
      if (reQueryParamBuilder_ == null) {
        reQueryParam_ = builderForValue.build();
        onChanged();
      } else {
        reQueryParamBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .hngdrpcdg.RecordQueryParam reQueryParam = 2;</code>
     */
    public Builder mergeReQueryParam(com.hngd.rpc.dg.RecordQueryParam value) {
      if (reQueryParamBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002) &&
            reQueryParam_ != null &&
            reQueryParam_ != com.hngd.rpc.dg.RecordQueryParam.getDefaultInstance()) {
          reQueryParam_ =
            com.hngd.rpc.dg.RecordQueryParam.newBuilder(reQueryParam_).mergeFrom(value).buildPartial();
        } else {
          reQueryParam_ = value;
        }
        onChanged();
      } else {
        reQueryParamBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .hngdrpcdg.RecordQueryParam reQueryParam = 2;</code>
     */
    public Builder clearReQueryParam() {
      if (reQueryParamBuilder_ == null) {
        reQueryParam_ = null;
        onChanged();
      } else {
        reQueryParamBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }
    /**
     * <code>optional .hngdrpcdg.RecordQueryParam reQueryParam = 2;</code>
     */
    public com.hngd.rpc.dg.RecordQueryParam.Builder getReQueryParamBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getReQueryParamFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .hngdrpcdg.RecordQueryParam reQueryParam = 2;</code>
     */
    public com.hngd.rpc.dg.RecordQueryParamOrBuilder getReQueryParamOrBuilder() {
      if (reQueryParamBuilder_ != null) {
        return reQueryParamBuilder_.getMessageOrBuilder();
      } else {
        return reQueryParam_ == null ?
            com.hngd.rpc.dg.RecordQueryParam.getDefaultInstance() : reQueryParam_;
      }
    }
    /**
     * <code>optional .hngdrpcdg.RecordQueryParam reQueryParam = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.hngd.rpc.dg.RecordQueryParam, com.hngd.rpc.dg.RecordQueryParam.Builder, com.hngd.rpc.dg.RecordQueryParamOrBuilder> 
        getReQueryParamFieldBuilder() {
      if (reQueryParamBuilder_ == null) {
        reQueryParamBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.hngd.rpc.dg.RecordQueryParam, com.hngd.rpc.dg.RecordQueryParam.Builder, com.hngd.rpc.dg.RecordQueryParamOrBuilder>(
                getReQueryParam(),
                getParentForChildren(),
                isClean());
        reQueryParam_ = null;
      }
      return reQueryParamBuilder_;
    }

    private int perSecs_ ;
    /**
     * <pre>
     *循环周期，单位：秒
     * </pre>
     *
     * <code>optional int32 perSecs = 3;</code>
     */
    public boolean hasPerSecs() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     *循环周期，单位：秒
     * </pre>
     *
     * <code>optional int32 perSecs = 3;</code>
     */
    public int getPerSecs() {
      return perSecs_;
    }
    /**
     * <pre>
     *循环周期，单位：秒
     * </pre>
     *
     * <code>optional int32 perSecs = 3;</code>
     */
    public Builder setPerSecs(int value) {
      bitField0_ |= 0x00000004;
      perSecs_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *循环周期，单位：秒
     * </pre>
     *
     * <code>optional int32 perSecs = 3;</code>
     */
    public Builder clearPerSecs() {
      bitField0_ = (bitField0_ & ~0x00000004);
      perSecs_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object taskID_ = "";
    /**
     * <pre>
     *任务ID（CMS根据任务ID关联查询应答）
     * </pre>
     *
     * <code>optional string taskID = 4;</code>
     */
    public boolean hasTaskID() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     *任务ID（CMS根据任务ID关联查询应答）
     * </pre>
     *
     * <code>optional string taskID = 4;</code>
     */
    public java.lang.String getTaskID() {
      java.lang.Object ref = taskID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          taskID_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *任务ID（CMS根据任务ID关联查询应答）
     * </pre>
     *
     * <code>optional string taskID = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTaskIDBytes() {
      java.lang.Object ref = taskID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *任务ID（CMS根据任务ID关联查询应答）
     * </pre>
     *
     * <code>optional string taskID = 4;</code>
     */
    public Builder setTaskID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      taskID_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *任务ID（CMS根据任务ID关联查询应答）
     * </pre>
     *
     * <code>optional string taskID = 4;</code>
     */
    public Builder clearTaskID() {
      bitField0_ = (bitField0_ & ~0x00000008);
      taskID_ = getDefaultInstance().getTaskID();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *任务ID（CMS根据任务ID关联查询应答）
     * </pre>
     *
     * <code>optional string taskID = 4;</code>
     */
    public Builder setTaskIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      taskID_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:hngdrpcdg.PerTaskRequest)
  }

  // @@protoc_insertion_point(class_scope:hngdrpcdg.PerTaskRequest)
  private static final com.hngd.rpc.dg.PerTaskRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.hngd.rpc.dg.PerTaskRequest();
  }

  public static com.hngd.rpc.dg.PerTaskRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<PerTaskRequest>
      PARSER = new com.google.protobuf.AbstractParser<PerTaskRequest>() {
    public PerTaskRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new PerTaskRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PerTaskRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PerTaskRequest> getParserForType() {
    return PARSER;
  }

  public com.hngd.rpc.dg.PerTaskRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

