// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dgAPi.proto

package com.hngd.rpc.dg;

public interface QuryConfigRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hngdrpcdg.QuryConfigRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *设备信息
   * </pre>
   *
   * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
   */
  boolean hasDevInfo();
  /**
   * <pre>
   *设备信息
   * </pre>
   *
   * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
   */
  com.hngd.rpc.dg.DeviceInfo getDevInfo();
  /**
   * <pre>
   *设备信息
   * </pre>
   *
   * <code>required .hngdrpcdg.DeviceInfo devInfo = 1;</code>
   */
  com.hngd.rpc.dg.DeviceInfoOrBuilder getDevInfoOrBuilder();

  /**
   * <pre>
   *任务ID（CMS根据任务ID关联查询应答）
   * </pre>
   *
   * <code>optional string taskID = 2;</code>
   */
  boolean hasTaskID();
  /**
   * <pre>
   *任务ID（CMS根据任务ID关联查询应答）
   * </pre>
   *
   * <code>optional string taskID = 2;</code>
   */
  java.lang.String getTaskID();
  /**
   * <pre>
   *任务ID（CMS根据任务ID关联查询应答）
   * </pre>
   *
   * <code>optional string taskID = 2;</code>
   */
  com.google.protobuf.ByteString
      getTaskIDBytes();
}
