// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dgAPi.proto

package com.hngd.rpc.dg;

public interface RecordQueryParamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hngdrpcdg.RecordQueryParam)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 subStream = 1;</code>
   */
  boolean hasSubStream();
  /**
   * <code>optional int32 subStream = 1;</code>
   */
  int getSubStream();

  /**
   * <pre>
   * 文件类型 Time|Alarm|Manual|All
   * </pre>
   *
   * <code>optional string fileType = 2;</code>
   */
  boolean hasFileType();
  /**
   * <pre>
   * 文件类型 Time|Alarm|Manual|All
   * </pre>
   *
   * <code>optional string fileType = 2;</code>
   */
  java.lang.String getFileType();
  /**
   * <pre>
   * 文件类型 Time|Alarm|Manual|All
   * </pre>
   *
   * <code>optional string fileType = 2;</code>
   */
  com.google.protobuf.ByteString
      getFileTypeBytes();

  /**
   * <code>optional int64 startTime = 3;</code>
   */
  boolean hasStartTime();
  /**
   * <code>optional int64 startTime = 3;</code>
   */
  long getStartTime();

  /**
   * <code>optional int64 endTime = 4;</code>
   */
  boolean hasEndTime();
  /**
   * <code>optional int64 endTime = 4;</code>
   */
  long getEndTime();
}
