debug: true
spring:
  application:
    name: task-processor
  datasource:
        name: test
        url: jdbc:postgresql://192.168.0.142:5432/task
        username: postgres
        password: Admin12345
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.postgresql.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        
mybatis:
  mapper-locations: 
    - /com/hngd/mapping/*.xml
  type-aliases-package: com.hngd.model 
server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.144:12331/eureka,http://192.168.0.144:12332/eureka
  instance:
    hostname: 192.168.0.249
logging:
   config: ./config/log4j.xml
lts:
   jobclient:
      cluster-name: test_cluster
      registry-address: zookeeper://192.168.8.128:2181
      node-group: test_jobClient
      use-retry-client: true
      configs: 
        job:
          fail:
            store: mapdb
   tasktracker:
      cluster-name: test_cluster
      registry-address: zookeeper://192.168.8.128:2181
      node-group: test_trade_TaskTracker
      job-runner-class: com.hngd.service.impl.JobRunnerImpl
      configs: 
        job:
          fail:
            store: mapdb
   jobtracker:
    cluster-name: test_cluster
    listen-port: 35001
    registry-address: zookeeper://192.168.8.128:2181
    configs:
      job:
        logger: mysql
        queue: mysql
      jdbc:
        url: jdbc:mysql://127.0.0.1:3306/lts
        username: root
        password: root

 